const dnbSounds = [
    "Acidline/alinec11.WAV", "Acidline/alinec12.WAV", "Acidline/alinec13.WAV", "Acidline/alinec14.WAV", "Acidline/alinec15.WAV",
    "Acidline/alinec16.WAV", "Acidline/alinec17.WAV", "Acidline/alinec21.WAV", "Acidline/alinec22.WAV", "Acidline/alinec23.WAV",
    "Acidline/alinec24.WAV", "Acidline/alinec25.WAV", "Acidline/alinec26.WAV", "Acidline/alinec27.WAV", "Acidline/alinec31.WAV",
    "Acidline/alinec32.WAV", "Acidline/alinec33.WAV", "Acidline/alinec34.WAV", "Acidline/alinec35.WAV", "Acidline/alinec36.WAV",
    "Acidline/alinec37.WAV", "Acidline/alinee11.WAV", "Acidline/alinee12.WAV", "Acidline/alinee13.WAV", "Acidline/alinee14.WAV",
    "Acidline/alinee15.WAV", "Acidline/alinee16.WAV", "Acidline/alinee17.WAV", "Acidline/alinef11.WAV", "Acidline/alinef12.WAV",
    "Acidline/alinef13.WAV", "Acidline/alinef14.WAV", "Acidline/alinef15.WAV", "Acidline/alinef16.WAV", "Acidline/alinef17.WAV",
    "Acidline/alinef21.WAV", "Acidline/alinef22.WAV", "Acidline/alinef23.WAV", "Acidline/alinef24.WAV", "Acidline/alinef25.WAV",
    "Acidline/alinef26.WAV", "Acidline/alinef27.WAV", "Acidline/alineh11.WAV", "Acidline/alineh12.WAV", "Acidline/alineh13.WAV",
    "Acidline/alineh14.WAV", "Acidline/alineh15.WAV", "Acidline/alineh16.WAV", "Acidline/alineh17.WAV", "Acidline/alinej11.WAV",
    "Acidline/alinej12.WAV", "Acidline/alinej13.WAV", "Acidline/alinej14.WAV", "Acidline/alinej15.WAV", "Acidline/alinej16.WAV",
    "Acidline/alinej17.WAV", "Acidline/alinej21.WAV", "Acidline/alinej22.WAV", "Acidline/alinej23.WAV", "Acidline/alinej24.WAV",
    "Acidline/alinej25.WAV", "Acidline/alinej26.WAV", "Acidline/alinej27.WAV", "Acidline/alinej31.WAV", "Acidline/alinej32.WAV",
    "Acidline/alinej33.WAV", "Acidline/alinej34.WAV", "Acidline/alinej35.WAV", "Acidline/alinej36.WAV", "Acidline/alinej37.WAV",
    "Acidline/alinej41.WAV", "Acidline/alinej42.WAV", "Acidline/alinej43.WAV", "Acidline/alinej44.WAV", "Acidline/alinej45.WAV",
    "Acidline/alinej46.WAV", "Acidline/alinej47.WAV", "Acidline/alinek31.WAV", "Acidline/alinek32.WAV", "Acidline/alinek33.WAV",
    "Acidline/alinek34.WAV", "Acidline/alinek35.WAV", "Acidline/alinek36.WAV", "Acidline/alinek37.WAV", "Acidline/alinel11.WAV",
    "Acidline/alinel12.WAV", "Acidline/alinel13.WAV", "Acidline/alinel14.WAV", "Acidline/alinel15.WAV", "Acidline/alinel16.WAV",
    "Acidline/alinel17.WAV", "Acidline/alinem11.WAV", "Acidline/alinem12.WAV", "Acidline/alinem13.WAV", "Acidline/alinem14.WAV",
    "Acidline/alinem15.WAV", "Acidline/alinem16.WAV", "Acidline/alinem17.WAV", "Acidline/alinen11.WAV", "Acidline/alinen12.WAV",
    "Acidline/alinen13.WAV", "Acidline/alinen14.WAV", "Acidline/alinen15.WAV", "Acidline/alinen16.WAV", "Acidline/alinen17.WAV",
    "Acidline/alineo31.WAV", "Acidline/alineo32.WAV", "Acidline/alineo33.WAV", "Acidline/alineo34.WAV", "Acidline/alineo35.WAV",
    "Acidline/alineo36.WAV", "Acidline/alineo37.WAV", "Acidline/alinep21.WAV", "Acidline/alinep22.WAV", "Acidline/alinep23.WAV",
    "Acidline/alinep24.WAV", "Acidline/alinep25.WAV", "Acidline/alinep26.WAV", "Acidline/alinep27.WAV", "Acidline/bassy21.WAV", 
    "Acidline/bassy22.WAV", "Acidline/bassy23.WAV", "Acidline/bassy24.WAV", "Acidline/bassy25.WAV", "Acidline/bassy26.WAV", 
    "Acidline/bassy27.WAV", "Acidline/bassy31.WAV", "Acidline/bassy32.WAV", "Acidline/bassy33.WAV", "Acidline/bassy34.WAV", 
    "Acidline/bassy35.WAV", "Acidline/bassy36.WAV", "Acidline/bassy37.WAV", "Acidline/bitter11.WAV", "Acidline/bitter12.WAV", 
    "Acidline/bitter13.WAV", "Acidline/bitter14.WAV", "Acidline/bitter15.WAV", "Acidline/bitter16.WAV", "Acidline/bitter17.WAV", 
    "Acidline/frazb11.WAV", "Acidline/frazb12.WAV", "Acidline/frazb13.WAV", "Acidline/frazb14.WAV", "Acidline/frazb15.WAV", 
    "Acidline/frazb16.WAV", "Acidline/frazb17.WAV", "Acidline/frazb21.WAV", "Acidline/frazb22.WAV", "Acidline/frazb23.WAV", 
    "Acidline/frazb24.WAV", "Acidline/frazb25.WAV", "Acidline/frazb26.WAV", "Acidline/frazb27.WAV", "Acidline/frazb31.WAV", 
    "Acidline/frazb32.WAV", "Acidline/frazb33.WAV", "Acidline/frazb34.WAV", "Acidline/frazb35.WAV", "Acidline/frazb36.WAV", 
    "Acidline/frazb37.WAV", "Acidline/frazc11.WAV", "Acidline/frazc12.WAV", "Acidline/frazc13.WAV", "Acidline/frazc14.WAV", 
    "Acidline/frazc15.WAV", "Acidline/frazc16.WAV", "Acidline/frazc17.WAV", "Acidline/frazc21.WAV", "Acidline/frazc22.WAV", 
    "Acidline/frazc23.WAV", "Acidline/frazc24.WAV", "Acidline/frazc25.WAV", "Acidline/frazc26.WAV", "Acidline/frazc27.WAV", 
    "Acidline/frazc41.WAV", "Acidline/frazc42.WAV", "Acidline/frazc43.WAV", "Acidline/frazc44.WAV", "Acidline/frazc45.WAV", 
    "Acidline/frazc46.WAV", "Acidline/frazc47.WAV", "Acidline/hardcore11.WAV", "Acidline/hardcore12.WAV", "Acidline/hardcore13.WAV",
    "Acidline/hardcore14.WAV", "Acidline/hardcore15.WAV", "Acidline/hardcore16.WAV", "Acidline/hardcore17.WAV",
    "Acidline/phantom11.WAV", "Acidline/phantom12.WAV", "Acidline/phantom13.WAV", "Acidline/phantom14.WAV", "Acidline/phantom15.WAV",
    "Acidline/phantom16.WAV", "Acidline/phantom17.WAV", "Acidline/phantom21.WAV", "Acidline/phantom22.WAV", "Acidline/phantom23.WAV",
    "Acidline/phantom24.WAV", "Acidline/phantom25.WAV", "Acidline/phantom26.WAV", "Acidline/phantom27.WAV", "Arp/arpy11.WAV",
    "Arp/arpy12.WAV", "Arp/arpy13.WAV", "Arp/arpy14.WAV", "Arp/arpy15.WAV", "Arp/arpy16.WAV", "Arp/arpy17.WAV", "Arp/bop11.WAV",
    "Arp/bop12.WAV", "Arp/bop13.WAV", "Arp/bop14.WAV", "Arp/bop15.WAV", "Arp/bop16.WAV", "Arp/bop17.WAV", "Arp/bopc11.WAV",
    "Arp/bopc12.WAV", "Arp/bopc13.WAV", "Arp/bopc14.WAV", "Arp/bopc15.WAV", "Arp/bopc16.WAV", "Arp/bopc17.WAV", "Arp/flower11.WAV",
    "Arp/flower12.WAV", "Arp/flower13.WAV", "Arp/flower14.WAV", "Arp/flower15.WAV", "Arp/flower16.WAV", "Arp/flower17.WAV",
    "Arp/flower21.WAV", "Arp/flower22.WAV", "Arp/flower23.WAV", "Arp/flower24.WAV", "Arp/flower25.WAV", "Arp/flower26.WAV",
    "Arp/flower27.WAV", "Arp/panb11.WAV", "Arp/panb12.WAV", "Arp/panb13.WAV", "Arp/panb14.WAV", "Arp/panb15.WAV", "Arp/panb16.WAV",
    "Arp/panb17.WAV", "Arp/super11.WAV", "Arp/super12.WAV", "Arp/super13.WAV", "Arp/super14.WAV", "Arp/super15.WAV",
    "Arp/super16.WAV", "Arp/super17.WAV", "Arp/super21.WAV", "Arp/super22.WAV", "Arp/super23.WAV", "Arp/super24.WAV",
    "Arp/super25.WAV", "Arp/super26.WAV", "Arp/super27.WAV", "Arp/super31.WAV", "Arp/super32.WAV", "Arp/super33.WAV",
    "Arp/super34.WAV", "Arp/super35.WAV", "Arp/super36.WAV", "Arp/super37.WAV", "Arp/tunnel11.WAV", "Arp/tunnel12.WAV",
    "Arp/tunnel13.WAV", "Arp/tunnel14.WAV", "Arp/tunnel15.WAV", "Arp/tunnel16.WAV", "Arp/tunnel17.WAV", "Bass/AAA1.wav",
    "Bass/AAA2.wav", "Bass/AAA3.wav", "Bass/AAA4.wav", "Bass/AAA5.wav", "Bass/AAA6.wav", "Bass/AAA7.wav",
    "Bass/ABA1.wav", "Bass/ABA2.wav", "Bass/ABA3.wav", "Bass/ABA4.wav", "Bass/ABA5.wav", "Bass/ABA6.wav",
    "Bass/ABA7.wav", "Bass/ACC1.wav", "Bass/ACC2.wav", "Bass/ACC3.wav", "Bass/ACC4.wav", "Bass/ACC5.wav",
    "Bass/ACC6.wav", "Bass/ACC7.wav", "Bass/BABY1.wav", "Bass/BABY2.wav", "Bass/BABY3.wav", "Bass/BABY4.wav",
    "Bass/BABY5.wav", "Bass/BABY6.wav", "Bass/BABY7.wav", "Bass/BALL1.wav", "Bass/BALL2.wav", "Bass/BALL3.wav",
    "Bass/BALL4.wav", "Bass/BALL5.wav", "Bass/BALL6.wav", "Bass/BALL7.wav", "Bass/BASSA1.wav", "Bass/BASSA2.wav",
    "Bass/BASSA3.wav", "Bass/BASSA4.wav", "Bass/BASSA5.wav", "Bass/BASSA6.wav", "Bass/BASSA7.wav", "Bass/BASSB1.wav",
    "Bass/BASSB2.wav", "Bass/BASSB3.wav", "Bass/BASSB4.wav", "Bass/BASSB5.wav", "Bass/BASSB6.wav", "Bass/BASSB7.wav",
    "Bass/BASSG1.wav", "Bass/BASSG2.wav", "Bass/BASSG3.wav", "Bass/BASSG4.wav", "Bass/BASSG5.wav", "Bass/BASSG6.wav",
    "Bass/BASSG7.wav", "Bass/BASSH1.wav", "Bass/BASSH2.wav", "Bass/BASSH3.wav", "Bass/BASSH4.wav", "Bass/BASSH5.wav",
    "Bass/BASSH6.wav", "Bass/BASSH7.wav", "Bass/bown21.WAV", "Bass/bown22.WAV", "Bass/bown23.WAV", "Bass/bown24.WAV",
    "Bass/bown25.WAV", "Bass/bown26.WAV", "Bass/bown27.WAV", "Bass/bubble11.WAV", "Bass/bubble12.WAV", "Bass/bubble13.WAV",
    "Bass/bubble14.WAV", "Bass/bubble15.WAV", "Bass/bubble16.WAV", "Bass/bubble17.WAV", "Bass/daonga11.WAV",
    "Bass/daonga12.WAV", "Bass/daonga13.WAV", "Bass/daonga14.WAV", "Bass/daonga15.WAV", "Bass/daonga16.WAV",
    "Bass/daonga17.WAV", "Bass/deepb11.WAV", "Bass/deepb12.WAV", "Bass/deepb13.WAV", "Bass/deepb14.WAV", "Bass/deepb15.WAV",
    "Bass/deepb16.WAV", "Bass/deepb17.WAV", "Bass/esaw11.WAV", "Bass/esaw12.WAV", "Bass/esaw13.WAV", "Bass/esaw14.WAV",
    "Bass/esaw15.WAV", "Bass/esaw16.WAV", "Bass/esaw17.WAV", "Bass/gotcha11.WAV", "Bass/gotcha12.WAV", "Bass/gotcha13.WAV",
    "Bass/gotcha14.WAV", "Bass/gotcha15.WAV", "Bass/gotcha16.WAV", "Bass/gotcha17.WAV", "Bass/gotcha21.WAV",
    "Bass/gotcha22.WAV", "Bass/gotcha23.WAV", "Bass/gotcha24.WAV", "Bass/gotcha25.WAV", "Bass/gotcha26.WAV",
    "Bass/gotcha27.WAV", "Bass/RONI1.wav", "Bass/RONI2.wav", "Bass/RONI3.wav", "Bass/RONI4.wav", "Bass/RONI5.wav",
    "Bass/RONI6.wav", "Bass/RONI7.wav", "Drum/AVANT.wav", "Drum/CLAVES1.wav", "Drum/CLAVES2.wav", "Drum/CONGAS1.wav",
    "Drum/CONGAS2.wav", "Drum/CONGAS3.wav", "Drum/CRASH1.wav", "Drum/CRASH2.wav", "Drum/CRASHA1.wav", "Drum/DRUMS1.wav",
    "Drum/DRUMS12.wav", "Drum/DRUMS14.wav", "Drum/DRUMS15.wav", "Drum/DRUMS17.wav", "Drum/DRUMS18.wav", "Drum/DRUMS2.wav",
    "Drum/DRUMS20.wav", "Drum/DRUMS21.wav", "Drum/DRUMS4.wav", "Drum/DRUMS5.wav", "Drum/DRUMS6.wav", "Drum/DRUMS7.wav",
    "Drum/DRUMS8.wav", "Drum/DRUMS9.wav", "Drum/HATS1.wav", "Drum/HATS10.wav", "Drum/HATS2.wav", "Drum/HATS3.wav",
    "Drum/HATS4.wav", "Drum/HATS5.wav", "Drum/HATS6.wav", "Drum/HATS7.wav", "Drum/HATS8.wav", "Drum/HATS9.wav",
    "Drum/HATSNARE.wav", "Drum/INTRO2.wav", "Drum/INTRO3.wav", "Drum/INTRO4.wav", "Drum/INTRO5.wav", "Drum/INTRO6.wav",
    "Drum/KIK10.wav", "Drum/KIK11.wav", "Drum/KIK12.wav", "Drum/KIK2.wav", "Drum/KIK3.wav", "Drum/KIK4.wav",
    "Drum/KIK5.wav", "Drum/KIK6.wav", "Drum/KIK7.wav", "Drum/KIK8.wav", "Drum/KIK9.wav", "Drum/KIKSN2.wav",
    "Drum/KIKSN3.wav", "Drum/KIKSN4.wav", "Drum/KIKSN5.wav", "Drum/KIKSN6.wav", "Drum/KIKSN8.wav", "Drum/LITESN.wav",
    "Drum/RATTLER2.wav", "Drum/RATTLER3.wav", "Drum/RATTLER4.wav", "Drum/RATTLER6.wav", "Drum/RATTLER7.wav",
    "Drum/RIDE1.wav", "Drum/RIDE2.wav", "Drum/SEWERKIK.wav", "Drum/SHAKER1.wav", "Drum/SHAKER2.wav", "Drum/SHAKER3.wav",
    "Drum/SNARE1.wav", "Drum/SNARE10.wav", "Drum/SNARE11.wav", "Drum/SNARE13.wav", "Drum/SNARE14.wav", "Drum/SNARE3.wav",
    "Drum/SNARE4.wav", "Drum/SNARE5.wav", "Drum/SNARE6.wav", "Drum/SNARE8.wav", "Drum/SNARE9.wav", "Drum/SSNARE1.wav",
    "Fx/amorph11.WAV", "Fx/amorph12.WAV", "Fx/amorph13.WAV", "Fx/amorph14.WAV", "Fx/amorph15.WAV", "Fx/amorph16.WAV",
    "Fx/amorph17.WAV", "Fx/amorph21.WAV", "Fx/amorph22.WAV", "Fx/amorph23.WAV", "Fx/amorph24.WAV", "Fx/amorph25.WAV",
    "Fx/amorph26.WAV", "Fx/amorph27.WAV", "Fx/amorph31.WAV", "Fx/amorph32.WAV", "Fx/amorph33.WAV", "Fx/amorph34.WAV",
    "Fx/amorph35.WAV", "Fx/amorph36.WAV", "Fx/amorph37.WAV", "Fx/amorph41.WAV", "Fx/amorph42.WAV", "Fx/amorph43.WAV",
    "Fx/amorph44.WAV", "Fx/amorph45.WAV", "Fx/amorph46.WAV", "Fx/amorph47.WAV", "Fx/APPLAUSE.wav", "Fx/ARC.wav",
    "Fx/BALROG.wav", "Fx/bing11.WAV", "Fx/bing12.WAV", "Fx/bing13.WAV", "Fx/bing14.WAV", "Fx/bing15.WAV",
    "Fx/bing16.WAV", "Fx/bing17.WAV", "Fx/BOMB.wav", "Fx/CARCRASH.wav", "Fx/CARSKID.wav", "Fx/F1.wav", "Fx/future11.WAV",
    "Fx/future12.WAV", "Fx/future13.WAV", "Fx/future14.WAV", "Fx/future15.WAV", "Fx/future16.WAV", "Fx/future17.WAV",
    "Fx/fxa1.WAV", "Fx/fxb1.WAV", "Fx/fxc1.WAV", "Fx/harter41.WAV", "Fx/harter42.WAV", "Fx/harter43.WAV",
    "Fx/harter44.WAV", "Fx/harter45.WAV", "Fx/harter46.WAV", "Fx/harter47.WAV", "Fx/JETFX.wav", "Fx/KAOS.wav",
    "Fx/POLICE.wav", "Fx/RAYGUN1.wav", "Fx/RAYGUN2.wav", "Fx/SCREAM.wav", "Fx/URANUS.wav", "Fx/UZI1.wav",
    "Fx/water11.WAV", "Fx/water12.WAV", "Fx/water13.WAV", "Fx/water14.WAV", "Fx/water15.WAV", "Fx/water16.WAV",
    "Fx/water17.WAV", "Fx/WHOOSH.wav", "Keyboard/BELLS1.wav", "Keyboard/BELLS2.wav", "Keyboard/BELLS3.wav",
    "Keyboard/BELLS4.wav", "Keyboard/BELLS5.wav", "Keyboard/BELLS6.wav", "Keyboard/BELLS7.wav", "Keyboard/BLIP1.wav",
    "Keyboard/BLIP2.wav", "Keyboard/BLIP3.wav", "Keyboard/BLIP4.wav", "Keyboard/BLIP5.wav", "Keyboard/BLIP6.wav",
    "Keyboard/BLIP7.wav", "Keyboard/HOP1.wav", "Keyboard/HOP2.wav", "Keyboard/HOP3.wav", "Keyboard/HOP4.wav",
    "Keyboard/HOP5.wav", "Keyboard/HOP6.wav", "Keyboard/HOP7.wav", "Keyboard/INTO1.wav", "Keyboard/INTO2.wav",
    "Keyboard/INTO3.wav", "Keyboard/INTO4.wav", "Keyboard/INTO5.wav", "Keyboard/INTO6.wav", "Keyboard/INTO7.wav",
    "Keyboard/JAX1.wav", "Keyboard/JAX2.wav", "Keyboard/JAX3.wav", "Keyboard/JAX4.wav", "Keyboard/JAX5.wav",
    "Keyboard/JAX6.wav", "Keyboard/JAX7.wav", "Keyboard/KISS1.wav", "Keyboard/KISS2.wav", "Keyboard/KISS3.wav",
    "Keyboard/KISS4.wav", "Keyboard/KISS5.wav", "Keyboard/KISS6.wav", "Keyboard/KISS7.wav", "Keyboard/LOVE1.wav",
    "Keyboard/LOVE2.wav", "Keyboard/LOVE3.wav", "Keyboard/LOVE4.wav", "Keyboard/LOVE5.wav", "Keyboard/LOVE6.wav",
    "Keyboard/LOVE7.wav", "Melody/analog11.WAV", "Melody/analog12.WAV", "Melody/analog13.WAV", "Melody/analog14.WAV",
    "Melody/analog15.WAV", "Melody/analog16.WAV", "Melody/analog17.WAV", "Melody/analog21.WAV", "Melody/analog22.WAV",
    "Melody/analog23.WAV", "Melody/analog24.WAV", "Melody/analog25.WAV", "Melody/analog26.WAV", "Melody/analog27.WAV",
    "Melody/analog31.WAV", "Melody/analog32.WAV", "Melody/analog33.WAV", "Melody/analog34.WAV", "Melody/analog35.WAV",
    "Melody/analog36.WAV", "Melody/analog37.WAV", "Melody/bbleep11.WAV", "Melody/bbleep12.WAV", "Melody/bbleep13.WAV",
    "Melody/bbleep14.WAV", "Melody/bbleep15.WAV", "Melody/bbleep16.WAV", "Melody/bbleep17.WAV", "Melody/bbleep21.WAV",
    "Melody/bbleep22.WAV", "Melody/bbleep23.WAV", "Melody/bbleep24.WAV", "Melody/bbleep25.WAV", "Melody/bbleep26.WAV",
    "Melody/bbleep27.WAV", "Melody/delyx11.WAV", "Melody/delyx12.WAV", "Melody/delyx13.WAV", "Melody/delyx14.WAV",
    "Melody/delyx15.WAV", "Melody/delyx16.WAV", "Melody/delyx17.WAV", "Melody/fasq11.WAV", "Melody/fasq12.WAV",
    "Melody/fasq13.WAV", "Melody/fasq14.WAV", "Melody/fasq15.WAV", "Melody/fasq16.WAV", "Melody/fasq17.WAV",
    "Melody/fish11.WAV", "Melody/fish12.WAV", "Melody/fish13.WAV", "Melody/fish14.WAV", "Melody/fish15.WAV",
    "Melody/fish16.WAV", "Melody/fish17.WAV", "Melody/fraza11.WAV", "Melody/fraza12.WAV", "Melody/fraza13.WAV",
    "Melody/fraza14.WAV", "Melody/fraza15.WAV", "Melody/fraza16.WAV", "Melody/fraza17.WAV", "Melody/fraza21.WAV",
    "Melody/fraza22.WAV", "Melody/fraza23.WAV", "Melody/fraza24.WAV", "Melody/fraza25.WAV", "Melody/fraza26.WAV",
    "Melody/fraza27.WAV", "Melody/fraza31.WAV", "Melody/fraza32.WAV", "Melody/fraza33.WAV", "Melody/fraza34.WAV",
    "Melody/fraza35.WAV", "Melody/fraza36.WAV", "Melody/fraza37.WAV", "Melody/hard11.WAV", "Melody/hard12.WAV",
    "Melody/hard13.WAV", "Melody/hard14.WAV", "Melody/hard15.WAV", "Melody/hard16.WAV", "Melody/hard17.WAV",
    "Melody/hard21.WAV", "Melody/hard22.WAV", "Melody/hard23.WAV", "Melody/hard24.WAV", "Melody/hard25.WAV",
    "Melody/hard26.WAV", "Melody/hard27.WAV", "Melody/hard31.WAV", "Melody/hard32.WAV", "Melody/hard33.WAV",
    "Melody/hard34.WAV", "Melody/hard35.WAV", "Melody/hard36.WAV", "Melody/hard37.WAV", "Melody/hero11.WAV",
    "Melody/hero12.WAV", "Melody/hero13.WAV", "Melody/hero14.WAV", "Melody/hero15.WAV", "Melody/hero16.WAV",
    "Melody/hero17.WAV", "Melody/hero21.WAV", "Melody/hero22.WAV", "Melody/hero23.WAV", "Melody/hero24.WAV",
    "Melody/hero25.WAV", "Melody/hero26.WAV", "Melody/hero27.WAV", "Melody/hero31.WAV", "Melody/hero32.WAV",
    "Melody/hero33.WAV", "Melody/hero34.WAV", "Melody/hero35.WAV", "Melody/hero36.WAV", "Melody/hero37.WAV",
    "Melody/hero41.WAV", "Melody/hero42.WAV", "Melody/hero43.WAV", "Melody/hero44.WAV", "Melody/hero45.WAV",
    "Melody/hero46.WAV", "Melody/hero47.WAV", "Melody/heyya11.WAV", "Melody/heyya12.WAV", "Melody/heyya13.WAV",
    "Melody/heyya14.WAV", "Melody/heyya15.WAV", "Melody/heyya16.WAV", "Melody/heyya17.WAV", "Melody/higher11.WAV",
    "Melody/higher12.WAV", "Melody/higher13.WAV", "Melody/higher14.WAV", "Melody/higher15.WAV", "Melody/higher16.WAV",
    "Melody/higher17.WAV", "Melody/housee11.WAV", "Melody/housee12.WAV", "Melody/housee13.WAV", "Melody/housee14.WAV",
    "Melody/housee15.WAV", "Melody/housee16.WAV", "Melody/housee17.WAV", "Melody/lonely11.WAV", "Melody/lonely12.WAV",
    "Melody/lonely13.WAV", "Melody/lonely14.WAV", "Melody/lonely15.WAV", "Melody/lonely16.WAV", "Melody/lonely17.WAV",
    "Melody/lonely21.WAV", "Melody/lonely22.WAV", "Melody/lonely23.WAV", "Melody/lonely24.WAV", "Melody/lonely25.WAV",
    "Melody/lonely26.WAV", "Melody/lonely27.WAV", "Melody/loved11.WAV", "Melody/loved12.WAV", "Melody/loved13.WAV",
    "Melody/loved14.WAV", "Melody/loved15.WAV", "Melody/loved16.WAV", "Melody/loved17.WAV", "Melody/loved31.WAV",
    "Melody/loved32.WAV", "Melody/loved33.WAV", "Melody/loved34.WAV", "Melody/loved35.WAV", "Melody/loved36.WAV",
    "Melody/mlight11.WAV", "Melody/mlight12.WAV", "Melody/mlight13.WAV", "Melody/mlight14.WAV", "Melody/mlight15.WAV",
    "Melody/mlight16.WAV", "Melody/mlight17.WAV", "Melody/mlight21.WAV", "Melody/mlight22.WAV", "Melody/mlight23.WAV",
    "Melody/mlight24.WAV", "Melody/mlight25.WAV", "Melody/mlight26.WAV", "Melody/mlight27.WAV", "Melody/mlight31.WAV",
    "Melody/mlight32.WAV", "Melody/mlight33.WAV", "Melody/mlight34.WAV", "Melody/mlight35.WAV", "Melody/mlight36.WAV",
    "Melody/mlight37.WAV", "Melody/recall11.WAV", "Melody/recall12.WAV", "Melody/recall13.WAV", "Melody/recall14.WAV",
    "Melody/recall15.WAV", "Melody/recall16.WAV", "Melody/recall17.WAV", "Melody/recall21.WAV", "Melody/recall22.WAV",
    "Melody/recall23.WAV", "Melody/recall24.WAV", "Melody/recall25.WAV", "Melody/recall26.WAV", "Melody/recall27.WAV",
    "Melody/tara11.WAV", "Melody/tara12.WAV", "Melody/tara13.WAV", "Melody/tara14.WAV", "Melody/tara15.WAV",
    "Melody/tara16.WAV", "Melody/tara17.WAV", "Melody/tara21.WAV", "Melody/tara22.WAV", "Melody/tara23.WAV",
    "Melody/tara24.WAV", "Melody/tara25.WAV", "Melody/tara26.WAV", "Melody/tara27.WAV", "Melody/terb11.WAV",
    "Melody/terb12.WAV", "Melody/terb13.WAV", "Melody/terb14.WAV", "Melody/terb15.WAV", "Melody/terb16.WAV",
    "Melody/terb17.WAV", "Melody/terb41.WAV", "Melody/terb42.WAV", "Melody/terb43.WAV", "Melody/terb44.WAV",
    "Melody/terb45.WAV", "Melody/terb46.WAV", "Melody/terb47.WAV", "Melody/yeah11.WAV", "Melody/yeah12.WAV",
    "Melody/yeah13.WAV", "Melody/yeah14.WAV", "Melody/yeah15.WAV", "Melody/yeah16.WAV", "Melody/yeah17.WAV",
    "Melody/yeah21.WAV", "Melody/yeah22.WAV", "Melody/yeah23.WAV", "Melody/yeah24.WAV", "Melody/yeah25.WAV",
    "Melody/yeah26.WAV", "Melody/yeah27.WAV", "Melody/yeah31.WAV", "Melody/yeah32.WAV", "Melody/yeah33.WAV",
    "Melody/yeah34.WAV", "Melody/yeah35.WAV", "Melody/yeah36.WAV", "Melody/yeah37.WAV", "Organ/duster11.WAV",
    "Organ/duster12.WAV", "Organ/duster13.WAV", "Organ/duster14.WAV", "Organ/duster15.WAV", "Organ/duster16.WAV",
    "Organ/duster17.WAV", "Organ/hchord11.WAV", "Organ/hchord12.WAV", "Organ/hchord13.WAV", "Organ/hchord14.WAV",
    "Organ/hchord15.WAV", "Organ/hchord16.WAV", "Organ/hchord17.WAV", "Organ/hchord31.WAV", "Organ/hchord32.WAV",
    "Organ/hchord33.WAV", "Organ/hchord34.WAV", "Organ/hchord35.WAV", "Organ/hchord36.WAV", "Organ/hchord37.WAV",
    "Organ/hchord41.WAV", "Organ/hchord42.WAV", "Organ/hchord43.WAV", "Organ/hchord44.WAV", "Organ/hchord45.WAV",
    "Organ/hchord46.WAV", "Organ/hchord47.WAV", "Organ/organy11.WAV", "Organ/organy12.WAV", "Organ/organy13.WAV",
    "Organ/organy14.WAV", "Organ/organy15.WAV", "Organ/organy16.WAV", "Organ/organy17.WAV", "Organ/orgax11.WAV",
    "Organ/orgax12.WAV", "Organ/orgax13.WAV", "Organ/orgax14.WAV", "Organ/orgax15.WAV", "Organ/orgax16.WAV",
    "Organ/orgax17.WAV", "Organ/power11.WAV", "Organ/power12.WAV", "Organ/power13.WAV", "Organ/power14.WAV",
    "Organ/power15.WAV", "Organ/power16.WAV", "Organ/power17.WAV", "Organ/raveo11.WAV", "Organ/raveo12.WAV",
    "Organ/raveo13.WAV", "Organ/raveo14.WAV", "Organ/raveo15.WAV", "Organ/raveo16.WAV", "Organ/raveo17.WAV",
    "Organ/STARSKY1.wav", "Organ/STARSKY2.wav", "Organ/STARSKY3.wav", "Organ/STARSKY4.wav", "Organ/STARSKY5.wav",
    "Organ/STARSKY6.wav", "Organ/STARSKY7.wav", "Organ/TRAIN1.wav", "Organ/TRAIN2.wav", "Organ/TRAIN3.wav",
    "Organ/TRAIN4.wav", "Organ/TRAIN5.wav", "Organ/TRAIN6.wav", "Organ/TRAIN7.wav", "Pad/ALPHA1.wav", "Pad/ALPHA2.wav",
    "Pad/ALPHA3.wav", "Pad/ALPHA4.wav", "Pad/ALPHA5.wav", "Pad/ALPHA6.wav", "Pad/ALPHA7.wav", "Pad/ESHER1.wav",
    "Pad/ESHER2.wav", "Pad/ESHER3.wav", "Pad/ESHER4.wav", "Pad/ESHER5.wav", "Pad/ESHER6.wav", "Pad/ESHER7.wav",
    "Pad/glory11.WAV", "Pad/glory12.WAV", "Pad/glory13.WAV", "Pad/glory14.WAV", "Pad/glory15.WAV", "Pad/glory16.WAV",
    "Pad/glory17.WAV", "Pad/LITE1.wav", "Pad/LITE2.wav", "Pad/LITE3.wav", "Pad/LITE4.wav", "Pad/LITE5.wav",
    "Pad/LITE6.wav", "Pad/LITE7.wav", "Pad/mudab11.WAV", "Pad/mudab12.WAV", "Pad/mudab13.WAV", "Pad/mudab14.WAV",
    "Pad/mudab15.WAV", "Pad/mudab16.WAV", "Pad/mudab17.WAV", "Pad/mudab21.WAV", "Pad/mudab22.WAV", "Pad/mudab23.WAV",
    "Pad/mudab24.WAV", "Pad/mudab25.WAV", "Pad/mudab26.WAV", "Pad/mudab27.WAV", "Pad/mudab31.WAV", "Pad/mudab32.WAV",
    "Pad/mudab33.WAV", "Pad/mudab34.WAV", "Pad/mudab35.WAV", "Pad/mudab36.WAV", "Pad/mudab37.WAV", "Pad/mudab41.WAV",
    "Pad/mudab42.WAV", "Pad/mudab43.WAV", "Pad/mudab44.WAV", "Pad/mudab45.WAV", "Pad/mudab46.WAV", "Pad/mudab47.WAV",
    "Pad/PAD1.wav", "Pad/PAD2.wav", "Pad/PAD3.wav", "Pad/PAD4.wav", "Pad/PAD5.wav", "Pad/PAD6.wav", "Pad/PAD7.wav",
    "Pad/PHAZER1.wav", "Pad/PHAZER2.wav", "Pad/PHAZER3.wav", "Pad/PHAZER4.wav", "Pad/PHAZER5.wav", "Pad/PHAZER6.wav",
    "Pad/PHAZER7.wav", "Pad/wax11.WAV", "Pad/wax12.WAV", "Pad/wax13.WAV", "Pad/wax14.WAV", "Pad/wax15.WAV",
    "Pad/wax16.WAV", "Pad/wax17.WAV", "Piano/SOYLENT1.wav", "Piano/SOYLENT2.wav", "Piano/SOYLENT3.wav", "Piano/SOYLENT4.wav",
    "Piano/SOYLENT5.wav", "Piano/SOYLENT6.wav", "Piano/SOYLENT7.wav", "Piano/TANGO1.wav", "Piano/TANGO2.wav",
    "Piano/TANGO3.wav", "Piano/TANGO4.wav", "Piano/TANGO5.wav", "Piano/TANGO6.wav", "Piano/TANGO7.wav", "Piano/TOY1.wav",
    "Piano/TOY2.wav", "Piano/TOY3.wav", "Piano/TOY4.wav", "Piano/TOY5.wav", "Piano/TOY6.wav", "Piano/TOY7.wav",
    "String/craze11.WAV", "String/craze12.WAV", "String/craze13.WAV", "String/craze14.WAV", "String/craze15.WAV",
    "String/craze16.WAV", "String/craze17.WAV", "String/dark11.WAV", "String/dark12.WAV", "String/dark13.WAV",
    "String/dark14.WAV", "String/dark15.WAV", "String/dark16.WAV", "String/dark17.WAV", "String/grusel11.WAV",
    "String/grusel12.WAV", "String/grusel13.WAV", "String/grusel14.WAV", "String/grusel15.WAV", "String/grusel16.WAV",
    "String/grusel17.WAV", "String/high11.WAV", "String/high12.WAV", "String/high13.WAV", "String/high14.WAV",
    "String/high15.WAV", "String/high16.WAV", "String/high17.WAV", "String/lead11.WAV", "String/lead12.WAV",
    "String/lead13.WAV", "String/lead14.WAV", "String/lead15.WAV", "String/lead16.WAV", "String/lead17.WAV",
    "String/mega11.WAV", "String/mega12.WAV", "String/mega13.WAV", "String/mega14.WAV", "String/mega15.WAV",
    "String/mega16.WAV", "String/mega17.WAV", "Synth/BEAM1.wav", "Synth/BEAM2.wav", "Synth/BEAM3.wav", "Synth/BEAM4.wav",
    "Synth/BEAM5.wav", "Synth/BEAM6.wav", "Synth/BEAM7.wav", "Synth/DUST1.wav", "Synth/DUST2.wav", "Synth/DUST3.wav",
    "Synth/DUST4.wav", "Synth/DUST5.wav", "Synth/DUST6.wav", "Synth/DUST7.wav", "Synth/JOJO1.wav", "Synth/JOJO2.wav",
    "Synth/JOJO3.wav", "Synth/JOJO4.wav", "Synth/JOJO5.wav", "Synth/JOJO6.wav", "Synth/JOJO7.wav", "Synth/NINJA1.wav",
    "Synth/NINJA2.wav", "Synth/NINJA3.wav", "Synth/NINJA4.wav", "Synth/NINJA5.wav", "Synth/NINJA6.wav", "Synth/NINJA7.wav",
    "Synth/PIXEL1.wav", "Synth/PIXEL2.wav", "Synth/PIXEL3.wav", "Synth/PIXEL4.wav", "Synth/PIXEL5.wav", "Synth/PIXEL6.wav",
    "Synth/PIXEL7.wav", "Synth/WAZ1.wav", "Synth/WAZ2.wav", "Synth/WAZ3.wav", "Synth/WAZ4.wav", "Synth/WAZ5.wav",
    "Synth/WAZ6.wav", "Synth/WAZ7.wav", "Synth/YURI1.wav", "Synth/YURI2.wav", "Synth/YURI3.wav", "Synth/YURI4.wav",
    "Synth/YURI5.wav", "Synth/YURI6.wav", "Synth/YURI7.wav", "Synth/ZANGA1.wav", "Synth/ZANGA2.wav", "Synth/ZANGA3.wav",
    "Synth/ZANGA4.wav", "Synth/ZANGA5.wav", "Synth/ZANGA6.wav", "Synth/ZANGA7.wav", "Synth/ZINGA1.wav", "Synth/ZINGA2.wav",
    "Synth/ZINGA3.wav", "Synth/ZINGA4.wav", "Synth/ZINGA5.wav", "Synth/ZINGA6.wav", "Synth/ZINGA7.wav", "Synth/ZONGA1.wav",
    "Synth/ZONGA2.wav", "Synth/ZONGA3.wav", "Synth/ZONGA4.wav", "Synth/ZONGA5.wav", "Synth/ZONGA6.wav", "Synth/ZONGA7.wav",
    "Vibes/COOL1.wav", "Vibes/COOL2.wav", "Vibes/COOL3.wav", "Vibes/COOL4.wav", "Vibes/COOL5.wav", "Vibes/COOL6.wav",
    "Vibes/COOL7.wav", "Vibes/VIBEA1.wav", "Vibes/VIBEA2.wav", "Vibes/VIBEA3.wav", "Vibes/VIBEA4.wav", "Vibes/VIBEA5.wav",
    "Vibes/VIBEA6.wav", "Vibes/VIBEA7.wav", "Vibes/VIBEB1.wav", "Vibes/VIBEB2.wav", "Vibes/VIBEB3.wav", "Vibes/VIBEB4.wav",
    "Vibes/VIBEB5.wav", "Vibes/VIBEB6.wav", "Vibes/VIBEB7.wav", "Vocal/ALIEN1.wav", "Vocal/BIGBRR.wav", "Vocal/BIGONE.wav",
    "Vocal/BIGTWO.wav", "Vocal/BRRRR.wav", "Vocal/BUMSHA01.wav", "Vocal/CHUTNI.wav", "Vocal/CUT.wav", "Vocal/DARTH.wav",
    "Vocal/DEMON.wav", "Vocal/DUGGA.wav", "Vocal/FUKK01.wav", "Vocal/HUCK.wav", "Vocal/JAQUES.wav", "Vocal/LUVPUFF.wav",
    "Vocal/MAGNET.wav", "Vocal/MINCE.wav", "Vocal/MUSTANG.wav", "Vocal/NAVGATOR.wav", "Vocal/NUTON.wav", "Vocal/OIOI.wav",
    "Vocal/PAINTIN.wav", "Vocal/PONT.wav", "Vocal/PUMA.wav", "Vocal/RUPGULLY.wav", "Vocal/RUSTY.wav", "Vocal/TOOLBAGS.wav",
    "Vocal/TROUSER.wav", "Vocal/WAHBAG.wav", "Vocal/WAKKA.wav", "Wind/FLUTE1.wav", "Wind/FLUTE2.wav", "Wind/FLUTE3.wav",
    "Wind/FLUTE4.wav", "Wind/FLUTE5.wav", "Wind/FLUTE6.wav", "Wind/FLUTE7.wav", "Wind/MINOS1.wav", "Wind/MINOS2.wav",
    "Wind/MINOS3.wav", "Wind/MINOS4.wav", "Wind/MINOS5.wav", "Wind/MINOS6.wav",
    "Wind/MINOS7.wav"
];

/*
var str = "HELLO WORLD";
var n = str.charCodeAt(0);
*/

function playAudio() {
    const r = Math.floor(Math.random()*dnbSounds.length);
    const nameOfSound = dnbSounds[r];
    const nameOfSoundPlaceholder = document.getElementById("nameOfSoundPlaceholder");
    nameOfSoundPlaceholder.innerText = nameOfSound;
    const audio = new Audio(`dnb/${nameOfSound}`);
    audio.play();
}